### ISSUE TITLE
svg custom class

### ISSUE THREAD

**Issue by riez** [Introvertuous/svelte-icons#29]
I think it would be nice if we can add custom class for the `svg` tag. Currently we can only change the viewBox properties.

P.S: this is not issue but i couldnt find discussion tab.

**Comment by AnxiousDarkly** [comment]
you actually cannot pass class selectors in as props in svelte at all, it is a major point of contention iirc.

**Comment by AnxiousDarkly** [comment]
https://github.com/sveltejs/svelte/issues/2870
